freebsd_instance:
  image: freebsd-12-1-release-amd64
task:
  name: FreeBSD
  env:
    JULIA_VERSION: 1
  install_script:
    - sh -c "$(fetch https://raw.githubusercontent.com/ararslan/CirrusCI.jl/main/bin/install.sh -o -)"
  build_script:
    - cirrusjl build
  test_script:
    - cirrusjl test
